In [1]:
import numpy as np

## load the data
raw_data = np.load('../dataset/full_dataset_200k.npz')
train_data, train_label, test_data, test_label = raw_data['train_data'], raw_data['train_label'], raw_data['test_data'], \
    raw_data['test_label']

## check the shape of the data
print(train_data.shape, train_label.shape)
print(test_data.shape, test_label.shape)

(200000, 21, 3) (200000, 11)
(50000, 21, 3) (50000, 11)


In [2]:
label_map = {
    0: 'call',
    1: 'dislike',
    2: 'fist',
    3: 'like',
    4: 'ok',
    5: 'one',
    6: 'palm',
    7: 'peace',
    8: 'rock',
    9: 'three',
    10: 'three2',
}


In [3]:
## show a data of the palm class (train_label=6)

sample = train_data[np.argmax(train_label, axis=1) == 6][0]

print(sample)

## get the mean absolute value
print(np.mean(np.abs(sample)))


[[-0.00835368  0.08333832  0.02246482]
 [ 0.01972158  0.06720808  0.0110712 ]
 [ 0.04839373  0.05301165  0.00284912]
 [ 0.07390016  0.03938413  0.00686876]
 [ 0.091334    0.02486701  0.00922317]
 [ 0.02342036 -0.00052224  0.00326164]
 [ 0.02839396 -0.02523342 -0.00254855]
 [ 0.03319443 -0.04682421 -0.01123443]
 [ 0.03303966 -0.05736016 -0.03536431]
 [ 0.00106288 -0.00524902  0.00516239]
 [ 0.00356518 -0.03721415 -0.01011843]
 [ 0.00186117 -0.0562139  -0.02611608]
 [ 0.00459281 -0.07152949 -0.04595782]
 [-0.0153759  -0.00134533 -0.00188984]
 [-0.01835628 -0.03095203 -0.01285448]
 [-0.01699879 -0.04880228 -0.02618797]
 [-0.01317684 -0.06460892 -0.04469381]
 [-0.03301865  0.01086632 -0.00811064]
 [-0.04024506 -0.01044674 -0.01141597]
 [-0.04514074 -0.02661595 -0.01906035]
 [-0.04585693 -0.04289053 -0.03160419]]
0.027802295356412373


In [4]:
sample = [21943, 12837, 123980, 222222, 222223, 222224]

In [5]:

%matplotlib tk
import matplotlib.pyplot as plt

## plot 5 sample in 3d space

fig = plt.figure()

for i, idx in enumerate(sample):
    sample = train_data[idx]

    ax = fig.add_subplot(2, 3, i + 1, projection='3d')
    ax.set_title(f'Class: {label_map[np.argmax(train_label[idx])]}')

    # plt.axis('off')
    ax.set_xticklabels([])
    ax.set_yticklabels([])
    ax.set_zticklabels([])

    ## set projection
    ax.view_init(elev=-90, azim=-90)

    ax.scatter(sample[:, 0], sample[:, 1], sample[:, 2], marker='o', c='C0')

    ## connect the fingers
    fingers = [
        [0, 1, 2, 3, 4],
        [0, 5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16],
        [0, 17, 18, 19, 20],
        [5, 9, 13, 17]
    ]

    for finger in fingers:
        ax.plot(sample[finger, 0], sample[finger, 1], sample[finger, 2], c='C1')

plt.show()


IndexError: index 222222 is out of bounds for axis 0 with size 200000